# Generated by Django 4.2.6 on 2023-10-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werken', '0002_alter_werken_icon_alter_werken_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werken',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icon/'),
        ),
        migrations.AlterField(
            model_name='werken',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
